services:
  redis:
    container_name: "redis"
    image: "redis:alpine"
    restart: always
    command: sh -c 'exec redis-server --appendonly yes --replica-read-only no --requirepass "$${IO_REDIS_PASSWORD}"'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    volumes:
      - ".data/redis:/data"

  postgres:
    image: "postgres:14"
    restart: always
    container_name: "pg"
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ".data/pg:/var/lib/postgresql/data"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: "rabbitmq"
    restart: always
    env_file:
      - ./.env
    volumes:
      - .data/rabbitmq/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/logs/:/var/log/rabbitmq/log

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: "api"
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - postgres
      - rabbitmq
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - .data/.wwebjs_auth:/app/.wwebjs_auth
      - .data/medias:/app/public
