import express from "express";
import isAuth from "../middleware/isAuth";
import * as SalesPipelineController from "../controllers/SalesPipelineController";

const salesPipelineRoutes = express.Router();

salesPipelineRoutes.get(
  "/portal/proposals/:token",
  SalesPipelineController.portalProposal
);
salesPipelineRoutes.post(
  "/portal/proposals/:token/approve",
  SalesPipelineController.approvePortalProposal
);
salesPipelineRoutes.get(
  "/portal/proposals/:token/document",
  SalesPipelineController.portalProposalDocument
);
salesPipelineRoutes.get(
  "/portal/proposals/:token/service-order",
  SalesPipelineController.portalServiceOrder
);
salesPipelineRoutes.get(
  "/sales/pipeline",
  isAuth,
  SalesPipelineController.index
);
salesPipelineRoutes.get(
  "/sales/pipeline-dashboard",
  isAuth,
  SalesPipelineController.dashboard
);
salesPipelineRoutes.get(
  "/sales/pipeline-followups",
  isAuth,
  SalesPipelineController.listStaleOpportunities
);
salesPipelineRoutes.post(
  "/sales/pipeline-followups/run",
  isAuth,
  SalesPipelineController.runAutomaticFollowUps
);
salesPipelineRoutes.get(
  "/sales/performance-goals",
  isAuth,
  SalesPipelineController.listPerformanceGoals
);
salesPipelineRoutes.post(
  "/sales/performance-goals",
  isAuth,
  SalesPipelineController.savePerformanceGoal
);
salesPipelineRoutes.get(
  "/sales/performance-goals-dashboard",
  isAuth,
  SalesPipelineController.performanceGoalsDashboard
);
salesPipelineRoutes.get(
  "/sales/proposals/:proposalId/document",
  isAuth,
  SalesPipelineController.proposalDocument
);
salesPipelineRoutes.put(
  "/sales/proposals/:proposalId",
  isAuth,
  SalesPipelineController.updateProposal
);
salesPipelineRoutes.post(
  "/sales/proposals/:proposalId/convert-service-order",
  isAuth,
  SalesPipelineController.convertProposalToServiceOrder
);
salesPipelineRoutes.get(
  "/sales/pipeline/:opportunityId/proposals",
  isAuth,
  SalesPipelineController.listProposals
);
salesPipelineRoutes.post(
  "/sales/pipeline/:opportunityId/proposals",
  isAuth,
  SalesPipelineController.createProposal
);
salesPipelineRoutes.get(
  "/sales/pipeline/:opportunityId",
  isAuth,
  SalesPipelineController.show
);
salesPipelineRoutes.post(
  "/sales/pipeline",
  isAuth,
  SalesPipelineController.store
);
salesPipelineRoutes.put(
  "/sales/pipeline/:opportunityId",
  isAuth,
  SalesPipelineController.update
);
salesPipelineRoutes.post(
  "/sales/pipeline/:opportunityId/convert-service-order",
  isAuth,
  SalesPipelineController.convertToServiceOrder
);

export default salesPipelineRoutes;
