import express from "express";
import isAuth from "../middleware/isAuth";
import * as ServiceOrderController from "../controllers/ServiceOrderController";
import rateLimit from "../middleware/rateLimit";

const serviceOrderRoutes = express.Router();
const serviceEmailRateLimit = rateLimit({ windowMs: 15 * 60 * 1000, max: 30 });

serviceOrderRoutes.get(
  "/service/attendants",
  isAuth,
  ServiceOrderController.listAttendants
);
serviceOrderRoutes.post(
  "/service/attendants",
  isAuth,
  ServiceOrderController.createAttendant
);
serviceOrderRoutes.put(
  "/service/attendants/:attendantId",
  isAuth,
  ServiceOrderController.updateAttendant
);
serviceOrderRoutes.get(
  "/service/teams",
  isAuth,
  ServiceOrderController.listServiceTeams
);
serviceOrderRoutes.post(
  "/service/teams",
  isAuth,
  ServiceOrderController.createServiceTeam
);
serviceOrderRoutes.put(
  "/service/teams/:serviceTeamId",
  isAuth,
  ServiceOrderController.updateServiceTeam
);
serviceOrderRoutes.get(
  "/service/inventory",
  isAuth,
  ServiceOrderController.listInventoryItems
);
serviceOrderRoutes.get(
  "/service/inventory-low-stock",
  isAuth,
  ServiceOrderController.listLowStockInventoryItems
);
serviceOrderRoutes.get(
  "/service/inventory-movements",
  isAuth,
  ServiceOrderController.listInventoryMovements
);
serviceOrderRoutes.get(
  "/service/inventory-reports/consumption",
  isAuth,
  ServiceOrderController.inventoryConsumptionReport
);
serviceOrderRoutes.get(
  "/service/inventory-reports/batches",
  isAuth,
  ServiceOrderController.inventoryBatchReport
);
serviceOrderRoutes.get(
  "/service/inventory-reports/costs",
  isAuth,
  ServiceOrderController.inventoryCostReport
);
serviceOrderRoutes.get(
  "/service/inventory-audit",
  isAuth,
  ServiceOrderController.listInventoryAuditLogs
);
serviceOrderRoutes.get(
  "/service/financial-audit",
  isAuth,
  ServiceOrderController.listFinancialAuditLogs
);
serviceOrderRoutes.get(
  "/service/types-audit",
  isAuth,
  ServiceOrderController.listServiceTypeAuditLogs
);
serviceOrderRoutes.post(
  "/service/inventory",
  isAuth,
  ServiceOrderController.createInventoryItem
);
serviceOrderRoutes.put(
  "/service/inventory/:itemId",
  isAuth,
  ServiceOrderController.updateInventoryItem
);
serviceOrderRoutes.delete(
  "/service/inventory/:itemId",
  isAuth,
  ServiceOrderController.deleteInventoryItem
);
serviceOrderRoutes.post(
  "/service/inventory/:itemId/adjust",
  isAuth,
  ServiceOrderController.adjustInventoryItem
);
serviceOrderRoutes.get(
  "/service/pests",
  isAuth,
  ServiceOrderController.listPests
);
serviceOrderRoutes.post(
  "/service/pests",
  isAuth,
  ServiceOrderController.createPest
);
serviceOrderRoutes.put(
  "/service/pests/:pestId",
  isAuth,
  ServiceOrderController.updatePest
);
serviceOrderRoutes.delete(
  "/service/pests/:pestId",
  isAuth,
  ServiceOrderController.deletePest
);
serviceOrderRoutes.get(
  "/service/types",
  isAuth,
  ServiceOrderController.listServiceTypes
);
serviceOrderRoutes.post(
  "/service/types",
  isAuth,
  ServiceOrderController.createServiceType
);
serviceOrderRoutes.put(
  "/service/types/:serviceTypeId",
  isAuth,
  ServiceOrderController.updateServiceType
);
serviceOrderRoutes.post(
  "/service/types/:serviceTypeId/duplicate",
  isAuth,
  ServiceOrderController.duplicateServiceType
);
serviceOrderRoutes.delete(
  "/service/types/:serviceTypeId",
  isAuth,
  ServiceOrderController.deleteServiceType
);
serviceOrderRoutes.get(
  "/service/orders",
  isAuth,
  ServiceOrderController.listOrders
);
serviceOrderRoutes.get(
  "/service/orders/export",
  isAuth,
  ServiceOrderController.exportOrders
);
serviceOrderRoutes.get(
  "/service/orders-dashboard",
  isAuth,
  ServiceOrderController.dashboard
);
serviceOrderRoutes.get(
  "/service/orders-financial-report",
  isAuth,
  ServiceOrderController.financialReport
);
serviceOrderRoutes.get(
  "/service/orders-monthly-closing",
  isAuth,
  ServiceOrderController.monthlyFinancialClosing
);
serviceOrderRoutes.get(
  "/service/orders-billing-reminders",
  isAuth,
  ServiceOrderController.billingReminderCandidates
);
serviceOrderRoutes.get(
  "/service/orders/:serviceOrderId",
  isAuth,
  ServiceOrderController.showOrder
);
serviceOrderRoutes.post(
  "/service/orders",
  isAuth,
  ServiceOrderController.createOrder
);
serviceOrderRoutes.put(
  "/service/orders/:serviceOrderId",
  isAuth,
  ServiceOrderController.updateOrder
);
serviceOrderRoutes.patch(
  "/service/orders/:serviceOrderId/occurrence",
  isAuth,
  ServiceOrderController.updateOrderOccurrence
);
serviceOrderRoutes.patch(
  "/service/orders/:serviceOrderId",
  isAuth,
  ServiceOrderController.patchOrder
);
serviceOrderRoutes.get(
  "/service/orders/:serviceOrderId/document",
  isAuth,
  ServiceOrderController.publicDocument
);
serviceOrderRoutes.get(
  "/service/orders/:serviceOrderId/document/internal",
  isAuth,
  ServiceOrderController.internalDocument
);
serviceOrderRoutes.post(
  "/service/orders/:serviceOrderId/notify",
  isAuth,
  serviceEmailRateLimit,
  ServiceOrderController.notifyOrder
);
serviceOrderRoutes.post(
  "/service/orders/:serviceOrderId/billing-reminder",
  isAuth,
  serviceEmailRateLimit,
  ServiceOrderController.sendBillingReminder
);

export default serviceOrderRoutes;
