import express from "express";
import isAuth from "../middleware/isAuth";
import * as ServiceOrderController from "../controllers/ServiceOrderController";

const serviceOrderRoutes = express.Router();

serviceOrderRoutes.get(
  "/service/attendants",
  isAuth,
  ServiceOrderController.listAttendants
);
serviceOrderRoutes.post(
  "/service/attendants",
  isAuth,
  ServiceOrderController.createAttendant
);
serviceOrderRoutes.put(
  "/service/attendants/:attendantId",
  isAuth,
  ServiceOrderController.updateAttendant
);
serviceOrderRoutes.get(
  "/service/inventory",
  isAuth,
  ServiceOrderController.listInventoryItems
);
serviceOrderRoutes.get(
  "/service/inventory-low-stock",
  isAuth,
  ServiceOrderController.listLowStockInventoryItems
);
serviceOrderRoutes.get(
  "/service/inventory-movements",
  isAuth,
  ServiceOrderController.listInventoryMovements
);
serviceOrderRoutes.get(
  "/service/inventory-audit",
  isAuth,
  ServiceOrderController.listInventoryAuditLogs
);
serviceOrderRoutes.get(
  "/service/financial-audit",
  isAuth,
  ServiceOrderController.listFinancialAuditLogs
);
serviceOrderRoutes.post(
  "/service/inventory",
  isAuth,
  ServiceOrderController.createInventoryItem
);
serviceOrderRoutes.put(
  "/service/inventory/:itemId",
  isAuth,
  ServiceOrderController.updateInventoryItem
);
serviceOrderRoutes.delete(
  "/service/inventory/:itemId",
  isAuth,
  ServiceOrderController.deleteInventoryItem
);
serviceOrderRoutes.post(
  "/service/inventory/:itemId/adjust",
  isAuth,
  ServiceOrderController.adjustInventoryItem
);
serviceOrderRoutes.get(
  "/service/types",
  isAuth,
  ServiceOrderController.listServiceTypes
);
serviceOrderRoutes.post(
  "/service/types",
  isAuth,
  ServiceOrderController.createServiceType
);
serviceOrderRoutes.put(
  "/service/types/:serviceTypeId",
  isAuth,
  ServiceOrderController.updateServiceType
);
serviceOrderRoutes.delete(
  "/service/types/:serviceTypeId",
  isAuth,
  ServiceOrderController.deleteServiceType
);
serviceOrderRoutes.get(
  "/service/orders",
  isAuth,
  ServiceOrderController.listOrders
);
serviceOrderRoutes.get(
  "/service/orders-dashboard",
  isAuth,
  ServiceOrderController.dashboard
);
serviceOrderRoutes.get(
  "/service/orders-financial-report",
  isAuth,
  ServiceOrderController.financialReport
);
serviceOrderRoutes.get(
  "/service/orders-monthly-closing",
  isAuth,
  ServiceOrderController.monthlyFinancialClosing
);
serviceOrderRoutes.get(
  "/service/orders-billing-reminders",
  isAuth,
  ServiceOrderController.billingReminderCandidates
);
serviceOrderRoutes.get(
  "/service/orders/:serviceOrderId",
  isAuth,
  ServiceOrderController.showOrder
);
serviceOrderRoutes.post(
  "/service/orders",
  isAuth,
  ServiceOrderController.createOrder
);
serviceOrderRoutes.put(
  "/service/orders/:serviceOrderId",
  isAuth,
  ServiceOrderController.updateOrder
);
serviceOrderRoutes.get(
  "/service/orders/:serviceOrderId/document",
  isAuth,
  ServiceOrderController.publicDocument
);
serviceOrderRoutes.get(
  "/service/orders/:serviceOrderId/document/internal",
  isAuth,
  ServiceOrderController.internalDocument
);
serviceOrderRoutes.post(
  "/service/orders/:serviceOrderId/notify",
  isAuth,
  ServiceOrderController.notifyOrder
);
serviceOrderRoutes.post(
  "/service/orders/:serviceOrderId/billing-reminder",
  isAuth,
  ServiceOrderController.sendBillingReminder
);

export default serviceOrderRoutes;
