import request from 'src/service/request'

export const ListarAtendentesServico = () => request({ url: '/service/attendants', method: 'get' })
export const CriarAtendenteServico = data => request({ url: '/service/attendants', method: 'post', data })
export const AlterarAtendenteServico = data => request({ url: `/service/attendants/${data.id}`, method: 'put', data })

export const ListarEstoqueServico = () => request({ url: '/service/inventory', method: 'get' })
export const ListarEstoqueBaixoServico = () => request({ url: '/service/inventory-low-stock', method: 'get' })
export const ListarMovimentacoesEstoqueServico = () => request({ url: '/service/inventory-movements', method: 'get' })
export const RelatorioConsumoEstoqueServico = params => request({ url: '/service/inventory-reports/consumption', method: 'get', params })
export const RelatorioLotesEstoqueServico = () => request({ url: '/service/inventory-reports/batches', method: 'get' })
export const RelatorioCustosEstoqueServico = params => request({ url: '/service/inventory-reports/costs', method: 'get', params })
export const ListarAuditoriaEstoqueServico = () => request({ url: '/service/inventory-audit', method: 'get' })
export const ListarAuditoriaFinanceiraServico = () => request({ url: '/service/financial-audit', method: 'get' })
export const ListarAuditoriaTiposServico = () => request({ url: '/service/types-audit', method: 'get' })
export const CriarItemEstoqueServico = data => request({ url: '/service/inventory', method: 'post', data })
export const AlterarItemEstoqueServico = data => request({ url: `/service/inventory/${data.id}`, method: 'put', data })
export const ExcluirItemEstoqueServico = id => request({ url: `/service/inventory/${id}`, method: 'delete' })
export const AjustarItemEstoqueServico = (id, data) => request({ url: `/service/inventory/${id}/adjust`, method: 'post', data })

export const ListarPragasServico = params => request({ url: '/service/pests', method: 'get', params })
export const CriarPragaServico = data => request({ url: '/service/pests', method: 'post', data })
export const AlterarPragaServico = data => request({ url: `/service/pests/${data.id}`, method: 'put', data })
export const ExcluirPragaServico = id => request({ url: `/service/pests/${id}`, method: 'delete' })

export const ListarTiposServico = params => request({ url: '/service/types', method: 'get', params })
export const CriarTipoServico = data => request({ url: '/service/types', method: 'post', data })
export const AlterarTipoServico = data => request({ url: `/service/types/${data.id}`, method: 'put', data })
export const DuplicarTipoServico = id => request({ url: `/service/types/${id}/duplicate`, method: 'post' })
export const ExcluirTipoServico = id => request({ url: `/service/types/${id}`, method: 'delete' })

export const ListarOrdensServico = params => request({ url: '/service/orders', method: 'get', params })
export const DashboardOrdensServico = params => request({ url: '/service/orders-dashboard', method: 'get', params })
export const RelatorioFinanceiroOrdensServico = params => request({ url: '/service/orders-financial-report', method: 'get', params })
export const BaixarRelatorioFinanceiroOrdensServico = params => request({ url: '/service/orders-financial-report', method: 'get', params: { ...params, format: 'csv' }, responseType: 'blob' })
export const FechamentoMensalOrdensServico = params => request({ url: '/service/orders-monthly-closing', method: 'get', params })
export const BaixarFechamentoMensalOrdensServico = params => request({ url: '/service/orders-monthly-closing', method: 'get', params: { ...params, format: 'csv' }, responseType: 'blob' })
export const ObterOrdemServico = id => request({ url: `/service/orders/${id}`, method: 'get' })
export const CriarOrdemServico = data => request({ url: '/service/orders', method: 'post', data })
export const AlterarOrdemServico = data => request({ url: `/service/orders/${data.id}`, method: 'put', data })
export const AlterarOcorrenciaOrdemServico = (id, data) => request({ url: `/service/orders/${id}/occurrence`, method: 'patch', data })
export const DocumentoOrdemServico = id => request({ url: `/service/orders/${id}/document`, method: 'get', responseType: 'blob' })
export const DocumentoInternoOrdemServico = id => request({ url: `/service/orders/${id}/document/internal`, method: 'get', responseType: 'blob' })
export const NotificarOrdemServico = (id, data) => request({ url: `/service/orders/${id}/notify`, method: 'post', data })
export const EnviarLembreteCobrancaOrdemServico = (id, data) => request({ url: `/service/orders/${id}/billing-reminder`, method: 'post', data })
